### ISSUE TITLE
help : a problem on PublishArrivedDelegate

### ISSUE THREAD

**Issue by muscle090620118** [stevenlovegrove/MqttDotNet#13]
I'm making a client with aspx Page, and I want to change a asp:Label‘s Text when PublishArrived.  
Code :
 bool client_PublishArrived(object sender, PublishArrivedArgs e)
 {
    msgLabel.Text=e.Payload;
    return true;
} 
code runs Smoothly ,But nothing happend after the Code executed. why?
Can it interact with an asp control ?

**Comment by stevenlovegrove** [comment]
I know nothing about asp.net, sorry. You should try logging to the console instead to try to isolate where the problem lies. GUI's sometimes dislike being changed from a different thread - that may be your problem here.

**Comment by iplusplus** [comment]
Have you set up your page properly to respond to the server side changes?
You can't push a change to a web page directly unless you're using
websockets.  You'd need some kind of call back from the web page.  I know
asp.net webforms does some of this sort of stuff for you, but not sure how
much.

If I were doing this, I'd have a client side timer triggering an ajax call
back to the server to check the state of a model.  You would, of course
need to be handling your session state to enable this to work properly.

**Comment by muscle090620118** [comment]
Thanks for all. I had added a timer to client side to solve this problem, and it worked.
