### ISSUE TITLE
WP8 SocketEx can not connect

### ISSUE THREAD

**Issue by alkimake** [stevenlovegrove/MqttDotNet#6]
On Windows Phone 8 SocketEx gets 0 Byte transfer when try to connect 
`>## ReceiveAsync, pending = True
  =# ReceiveAsync, LastOperation = Receive
<## EndRead, BytesTransferred = 0`

This issue is not the case when running on Windows 8

Eventually i get this log

`4/17/2013 - 2:12:24 PM - [ERROR]System.Exception: Unsupported Message Type
   at MqttLib.Core.Messages.MessageFactory.CreateMessage(Stream str, Byte header)
   at MqttLib.Core.StreamManager.listen(IAsyncResult asyncResult)`

**Comment by alkimake** [comment]
This issue can be ignored... The main problem is handling network exceptions before reading socket. I will update code when i have time.

**Comment by mmischitelli** [comment]
Has this issue been actually solved? I've downloaded the master brach and after integrating the project in my WinPhone8 app I'm still getting the same problem (0 bytes transferred and unsupported message type).
